name: Java CI Maven for clawerichika

on:
  push:
    branches: [ "main", "dev" ]
    tags: 
      - 'v*'
  pull_request:
    branches: [ "main", "dev" ]

# Donner la permission pour écrire dans les releases 
permissions: 
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # 1. Set up la version de Java
    - name: Set JVM 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    # 2. Donner les permission pour exécuter le script maven
    - name: Grant exuction permission for the mvnw
      run: chmod +x mvnw

    # 3. Lancer les tests 
    - name: Run the unitests
      run: ./mvnw clean test
    
    # 4. Généré le .jar
    - name: Build JAR file
      run: ./mvnw package -DskipTests # Skip les tests puisqu'on les a déjà fait juste avant

    # 5. Sauvegarder le JAR pour la release
    - name: Upload JAR file
      uses: actions/upload-artifact@v4
      with:
        name: clawerichika-jar
        path: target/clawerichika.jar
        retention-days: 1
    
    # 6. Création de la release
    - name: Create the release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v2
      with:
        files: target/*.jar
        generate_release_notes: true
  deploy:
    needs: build
    if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest


    steps:

    # 1. Récupère le .JAR
    - name: Download JAR artifact
      uses: actions/download-artifact@v4
      with:
        name: clawerichika-jar
    
    # 2. Envoie le fichier sur le server
    - name: Copy JAR via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: "clawerichika.jar"
        target: "/home/debian/bot"
        overwrite: true

    # 3. Connecte sur le serveur en ssh pour restart le serveur
    - name: Restart Bot via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        # La commande qui redémarre le service
        script: |
          sudo systemctl restart discord-bot
          echo "✅ Bot déployé et redémarré avec succès !"